# golangci-linter configuration
# See https://github.com/golangci/golangci-lint#config-file for reference.

run:
  go: "1.10"
  skip-dirs:
    - .github
    - bench
    - config
    - db
    - mocks
    - tls
    - vendor

linters-settings:
  errcheck:
    check-blank: true
  gocyclo:
    min-complexity: 20
  gosimple:
    go: "1.10"
  govet:
    check-shadowing: true
    enable:
      - assign
      - atomic
      - bool
      - composites
      - copylocks
      - lostcancel
      - nilfunc
      - printf
      - rangeloops
      - shift
      - unreachable
      - unusedresult
  lll:
    line-length: 140
    tab-width: 4
  misspell:
    locale: US
  stylecheck:
    go: "1.10"

linters:
  enable:
    - dupl
    - goconst
    - gocyclo
    - goimports
    - lll
    - misspell
    - prealloc
    - stylecheck
    - unconvert

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl