#
# Copyright (c) 2016 TFG Co <backend@tfgco.com>
# Author: TFG Co <backend@tfgco.com>
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

FROM golang:1.23-alpine

ARG TARGETARCH

ENV LIBRARY_PATH /usr/local/lib
ENV LD_LIBRARY_PATH /usr/local/lib

RUN sed -i -e 's/#community/community/g' /etc/apk/repositories \
    && apk update \
    && apk add --no-cache \
        wget \
        gnupg \
        build-base \
        librdkafka-dev \
        postgresql-client-libs \
        postgresql-dev \
    && rm -rf /var/cache/apk/*

# golangci-lint
ENV GOLANGCI_LINT_VERSION 2.1.6
RUN case "${TARGETARCH}" in \
        "amd64") GOLANGCI_LINT_DOWNLOAD_ARCH="amd64" ;; \
        "arm64") GOLANGCI_LINT_DOWNLOAD_ARCH="arm64" ;; \
        *) echo "Unsupported architecture for golangci-lint: ${TARGETARCH}"; exit 1 ;; \
    esac \
    && wget -O /go/bin/golangci-lint.tar.gz "https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_LINT_VERSION}/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-${GOLANGCI_LINT_DOWNLOAD_ARCH}.tar.gz" \
    && tar -xzf /go/bin/golangci-lint.tar.gz -C /go/bin \
    && mv "/go/bin/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-${GOLANGCI_LINT_DOWNLOAD_ARCH}/golangci-lint" /go/bin/ \
    && rm -rf "/go/bin/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-${GOLANGCI_LINT_DOWNLOAD_ARCH}" \
    && rm /go/bin/golangci-lint.tar.gz

# ginkgo
ENV GINKGO_VERSION 1.16.5
RUN go install github.com/onsi/ginkgo/ginkgo@v${GINKGO_VERSION}

WORKDIR /go/src/github.com/topfreegames/pusher

ADD . /go/src/github.com/topfreegames/pusher
